services:
  mi-mysql-2:
    container_name: mi-mysql-2
    networks:
      - mi-mysql-red-2
    volumes:
      - mi-mysql-vol:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    stdin_open: true # -i
    tty: true # -t
    image: mysql

  mi-dashboard-2:
    container_name: mi-dashboard-2
    networks:
      - mi-mysql-red-2
    environment:
      - PMA_HOST=mi-mysql
    ports:
      - 8080:80
    stdin_open: true # -i
    tty: true # -t
    image: phpmyadmin

networks:
  mi-mysql-red-2:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

volumes:
  mi-mysql-vol:
