services:
  mi-mongo:
    container_name: mi-mongo
    networks:
      - mi-red
    volumes:
      - mi-volumen:/data/db
    stdin_open: true # -i
    tty: true # -t
    image: mongo

  mi-mongo-express:
    container_name: mi-mongo-express
    networks:
      - mi-red
    environment:
      - ME_CONFIG_MONGODB_SERVER=mi-mongo
    ports:
      - 8081:8081
    stdin_open: true # -i
    tty: true # -t
    image: mongo-express

networks:
  mi-red:

volumes:
  mi-volumen:
